In [4]:
import pandas as pd, scipy, numpy as np
import sklearn.preprocessing


# ### Loading the iris dataset




headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class'] #Assigning the headers





ds = pd.read_csv('iris.csv', names = headernames)
ds.head()





print(ds)


# ### Splitting up in feature attributes and class variable




#x = ds.iloc[:, :-1].values 





y=ds.iloc[:, 4].values


# ### Train and Test Split
# Next, we will divide the data into train and test split. Following code will split the dataset into 60% training data and 40% of testing data




from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.40)


# ### Data Scaling using the StandardScaler




from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


# ### Training a KNN Classifier




from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 7)
classifier.fit(X_train, y_train)


# ### Making the Predictions




y_pred = classifier.predict(X_test)


# ### Output




from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)





Y_pred = classifier.predict(X_test)
print(Y_pred)


# ### K-fold Crossvalidation
# K-Folds cross-validator provides train/test indices to split data in train/test sets. Split dataset into k consecutive folds (without shuffling by default). Each fold is then used once as a validation while the k - 1 remaining folds form the training set.
# 
# more information on https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html




from sklearn.model_selection import KFold
# prepare cross validation
kfold = KFold(2, True) # value of K and shuffle? 
# enumerate splits
for train, test in kfold.split(X_train):
    print('train: %s, test: %s' % (X_train[train], X_train[test]))
   





for train, test in kfold.split(X_train):
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    result = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(result)
    result1 = classification_report(y_test, y_pred)
    print("Classification Report:",)
    print (result1)
    result2 = accuracy_score(y_test,y_pred)
    print("Accuracy:",result2)

     sepal-length  sepal-width  petal-length  petal-width           Class
1             5.1          3.5           1.4          0.2     Iris-setosa
2             4.9          3.0           1.4          0.2     Iris-setosa
3             4.7          3.2           1.3          0.2     Iris-setosa
4             4.6          3.1           1.5          0.2     Iris-setosa
5             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
146           6.7          3.0           5.2          2.3  Iris-virginica
147           6.3          2.5           5.0          1.9  Iris-virginica
148           6.5          3.0           5.2          2.0  Iris-virginica
149           6.2          3.4           5.4          2.3  Iris-virginica
150           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]
Confusion Matrix:
[[22  0  0]
 [ 0 18  4]
 [ 0  1 15]]
Classification Report:
          

C:\Users\hajra\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass shuffle=True as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
